// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT $1::int AS status
`

func (q *Queries) HealthCheck(ctx context.Context, dollar_1 int32) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck, dollar_1)
	var status int32
	err := row.Scan(&status)
	return status, err
}
