// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StopSign struct {
	ID       int32
	JarticID pgtype.Text
	Bearing  pgtype.Int4
	Geom     interface{}
}
