name: Discord Notify

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 GitHub Update: ${{ github.repository }} by ${{ github.actor }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
